version: '3'
services:
    web:
        env_file: 
            - ./docker.env
        image: nginx:alpine
        container_name: tts-nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    
    php:
        container_name: tts-php
        image: nanoninja/php-fpm:7.1
        restart: always
        volumes:
            - "./web:/var/www/html"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        depends_on:
            - mysqldb

    composer:
        image: "composer"
        volumes:
            - "./web/app:/app"
        command: install

    mysqldb:
        env_file: 
            - ./docker.env
        image: mysql:5.7
        container_name: tts-mysql
        restart: always
        ports:
            - "8989:3306"
        volumes:
            - ./data/db/dumps:/docker-entrypoint-initdb.d

    myadmin:
        env_file: docker.env
        image: phpmyadmin/phpmyadmin:4.8.1
        container_name: tts-phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        links:
            - mysqldb
        depends_on:
            - mysqldb
